kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
data:
  BASE_UPDATE_DESCRICAO: {{ .Values.sei.BASE_UPDATE_DESCRICAO }}
  SIP_BANCO_NOME: {{ .Values.sei.SIP_BANCO_NOME }}
  SEI_BANCO_USUARIO: {{ .Values.sei.SIP_BANCO_USUARIO }}
  BASE_UPDATE_WEB_SERVICE: {{ .Values.sei.BASE_UPDATE_WEB_SERVICE }}
  SIP_BANCO_USUARIO: {{ Values.sei.SIP_BANCO_USUARIO }}
  SEI_BANCO_NOME: {{ .Values.sei.SEI_BANCO_NOME }}
  SEI_URL: {{ .Values.sei.SEI_URL }}
  SIP_WSDL: {{ .Values.sei.SIP_WSDL }}
  SIP_URL: {{ .Values.sei.SIP_URL }}
  SOLR_SERVIDOR: {{ .Values.sei.SOLR_SERVIDOR }}
  JODCONVERTER_SERVIDOR: {{ .Values.sei.JODCONVERTER_SERVIDOR }}
  SIP_PAGINA_LOGIN: {{ .Values.sei.SIP_PAGINA_LOGIN }}
  EMAIL_SERVIDOR: {{ .Values.sei.EMAIL_SERVIDOR }}
  BANCO_SERVIDOR: {{ .Values.sei.BANCO_SERVIDOR }}
  SIP_PRODUCAO: {{ .Values.sei.SIP_PRODUCAO }}
  SEI_REPOSITORIO_ARQUIVOS: {{ .Values.sei.SEI_REPOSITORIO_ARQUIVOS }}
  SEI_PRODUCAO: {{ .Values.sei.SEI_PRODUCAO }}
  BASE_UPDATE_PAGINA_INICIAL_SEI: {{ .Values.sei.BASE_UPDATE_PAGINA_INICIAL_SEI }}
  BANCO_PORTA: {{ .Values.sei.BANCO_PORTA }}
  SEI_NOME_SISTEMA_COMPLETO: {{ .Values.sei.SEI_NOME_SISTEMA_COMPLETO }}
  BASE_UPDATE_SIGLA: {{ .Values.sei.BASE_UPDATE_SIGLA }}
  BASE_UPDATE_PAGINA_INICIAL_SIP: {{ .Values.sei.BASE_UPDATE_PAGINA_INICIAL_SIP }}