kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{.Values.namespace.name}}
  labels:
    appglobal: {{ .Release.Name }}
data:
  SEI_BANCO_SENHA: {{ .Values.sei.SEI_BANCO_SENHA }}
  SIP_BANCO_SENHA: {{ .Values.sei.SIP_BANCO_SENHA }}
type: Opaque