kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.apache.name }}
  namespace: {{.Values.namespace.name}}
  labels:
    app: {{ .Release.Name }}-{{ .Values.apache.name }}
    appglobal: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.apache.name }}
      deployment: {{ .Values.apache.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.apache.name }}
        deployment: {{ .Values.apache.name }}
    spec:
      volumes:
        - name: pvc-{{ .Release.Name }}-{{ .Values.apache.volume.name }}
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-{{ .Values.apache.volume.name }}
      {{ if eq .Values.sei.AMBIENTE "KUBERNETES" }}
      initContainers:
      - name: change-permissions-{{ .Release.Name }}-{{ .Values.apache.name }}
        image: busybox:1.28
        command: ['sh', '-c', "chown -R 100:0 {{ .Values.sei.SEI_REPOSITORIO_ARQUIVOS }}"]
        volumeMounts:
          - name: pvc-{{ .Release.Name }}-{{ .Values.apache.volume.name }}
            mountPath: {{ .Values.sei.SEI_REPOSITORIO_ARQUIVOS }}
      {{ end }}
      containers:
        - name: sei
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: pvc-{{ .Release.Name }}-{{ .Values.apache.volume.name }}
              mountPath: {{ .Values.sei.SEI_REPOSITORIO_ARQUIVOS }}
          image: {{ .Values.apache.image }}:{{ .Values.apache.tag }}
      restartPolicy: Always
