kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
  namespace: {{ .Values.namespace.name }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - {{ .Values.mysql.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.volume.size }}
  volumeMode: Filesystem